import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ShellBar } from "@ui5/webcomponents-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Dahill",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="">
                    <ShellBar
                        primaryTitle="Dahill Construction"
                        showProductSwitch
                    ></ShellBar>
                </div>

                {children}
            </body>
        </html>
    );
}
