import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ShellBar } from "@ui5/webcomponents-react";

const inter = Poppins({
    subsets: ["latin"],
    weight: "400"
});

export const metadata: Metadata = {
    title: "Schertech",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="">
                    <ShellBar
                        primaryTitle="Schertech"
                        showProductSwitch
                    ></ShellBar>
                </div>

                {children}
            </body>
        </html>
    );
}
